chore(package): update rollup-plugin-uglify
## Version **4.0.0** of [rollup-plugin-uglify](https://github.com/TrySound/rollup-plugin-uglify) was just published.

<table>
  <tr>
    <th align=left>
      Dependency
    </th>
    <td>
      <code>rollup-plugin-uglify</code>
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </th>
    <td>
      3.0.0
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </th>
    <td>
      devDependency
    </td>
  </tr>
</table>

The version **4.0.0** is **not covered** by your **current version range**.

If you don’t accept this pull request, your project will work just like it did before. However, you might be missing out on a bunch of new features, fixes and/or performance improvements from the dependency update.

It might be worth looking into these changes and trying to get this project onto the latest version of rollup-plugin-uglify.

If you have a solid test suite and good coverage, a passing build is a strong indicator that you can take advantage of these changes directly by merging the proposed change into your project. If the build fails or you don’t have such unconditional trust in your tests, this branch is a great starting point for you to work on the update.


---


<details>
<summary>Release Notes</summary>
<strong>v4 and back to es5</strong>

<p>uglify-es is not supported anymore so we returned back to old school uglify-js. If you still want to transpile es6+ try <a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-terser">rollup-plugin-terser</a>. <a href="https://urls.greenkeeper.io/fabiosantoscode/terser">Terser</a> is actively developed fork of uglify-es with the new name.</p>
<p>In this version we changed the way to import plugin. Now it looks like this</p>
<div class="highlight highlight-source-js"><pre><span class="pl-k">import</span> { <span class="pl-smi">uglify</span> } <span class="pl-k">from</span> <span class="pl-s"><span class="pl-pds">'</span>rollup-plugin-uglify<span class="pl-pds">'</span></span>;

<span class="pl-k">export</span> <span class="pl-c1">default</span> {
  <span class="pl-k">...</span>
  plugins<span class="pl-k">:</span> [<span class="pl-en">uglify</span>()]
  <span class="pl-k">...</span>
}</pre></div>
<p>To see more prettier errors uglify shows also babel code frame</p>
<pre><code>    &gt; 1 | var = 1
        |    ^ Name expected

Error: Error transforming bundle with 'uglify' plugin: Name expected
</code></pre>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 6 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/a847d2e4d6c63557d1dbc943b6b7586d5dbf2d96"><code>a847d2e</code></a> <code>4.0.0</code></li>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/cd8f9f137d45f778abf3a3a5fbfe101ef3af7e85"><code>cd8f9f1</code></a> <code>Change default export to named one</code></li>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/6e46a12c65279d7f8add14d3d6087d93fd162c80"><code>6e46a12</code></a> <code>Use uglify-js as uglify-es got deprecated in favour of terser (#42)</code></li>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/3beec8720d077e2adbdf033e0f61c47586aea5ce"><code>3beec87</code></a> <code>Merge pull request #40 from kzc/patch-1</code></li>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/5c0782637d863f596c3574b28d124d50fe54db67"><code>5c07826</code></a> <code>have README point to uglify-es docs</code></li>
<li><a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/commit/3dc760077cdbc44d8a3579333c949e9c3cfc9071"><code>3dc7600</code></a> <code>Fix tests</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/TrySound/rollup-plugin-uglify/compare/ba9c53f3e431d8e9f80278c74e2d66bac555b1ae...a847d2e4d6c63557d1dbc943b6b7586d5dbf2d96">full diff</a></p>
</details>

<details>
  <summary>FAQ and help</summary>

  There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---


Your [Greenkeeper](https://greenkeeper.io) bot :palm_tree: